POST http://localhost:1000/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Creating my second video.",
  "duration": "240"
}

### 

GET http://localhost:1000/videos

###

PUT http://localhost:1000/videos/e9371ce4-85da-4b5d-b956-10d89fdfd0be
Content-Type: application/json

{
  "title": "Video 03",
  "description": "Changing my second video.",
  "duration": "245"
}

###

DELETE http://localhost:1000/videos/53441567-dcdf-4a88-b230-d1103fef6013