POST http://localhost:1000/videos
Content-Type: application/json

{
  "title": "Video Node",
  "description": "Creating my second video.",
  "duration": "240"
}

### 
GET http://localhost:1000/videos?

###
PUT http://localhost:1000/videos/3be15817-382f-454a-8e03-0df16b47334a
Content-Type: application/json

{
  "title": "Video Node 03",
  "description": "Changing the node video again.",
  "duration": "250"
}

###
DELETE http://localhost:1000/videos/53441567-dcdf-4a88-b230-d1103fef6013