POST http://localhost:1000/videos
Content-Type: application/json

{
  "title": "Video Node",
  "description": "Creating my second video.",
  "duration": "240"
}

### 
GET http://localhost:1000/videos?search=Node

###
PUT http://localhost:1000/videos/e9371ce4-85da-4b5d-b956-10d89fdfd0be
Content-Type: application/json

{
  "title": "Video 03",
  "description": "Changing my second video.",
  "duration": "245"
}

###
DELETE http://localhost:1000/videos/a2bff8be-7d87-4215-be17-eefb8d5385af